/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    testimonials: Testimonial;
    brands: Brand;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'services-page': ServicesPage;
    'about-page': AboutPage;
    'booking-page': BookingPage;
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'booking-page': BookingPageSelect<false> | BookingPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Detailing packages and pricing. Drag to reorder. Shown on the Services page and wherever the Home page features them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * For example $299 or $99/month
   */
  price: string;
  /**
   * For example 4-6 hours
   */
  duration?: string | null;
  /**
   * Short description for the Home page package cards
   */
  summary: string;
  /**
   * Full description for the Services page
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos and logos used across the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo for screen readers and search engines
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Customer reviews shown on the Home page. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * For example Regular Client
   */
  title?: string | null;
  review: string;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Car brand logos shown on the Home page. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  _order?: string | null;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * People who can sign in to manage the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage users and all content. Editors manage content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  price?: T;
  duration?: T;
  summary?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  title?: T;
  review?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Rotating headlines. Drag to reorder.
     */
    slides: {
      /**
       * Small text above the heading
       */
      eyebrow: string;
      title: string;
      id?: string | null;
    }[];
    backgroundImage: number | Media;
    cta: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
    showPhone?: boolean | null;
    /**
     * For example Call Us:
     */
    phoneLabel: string;
    showAddress?: boolean | null;
  };
  servicesBar: {
    /**
     * The strip of services under the hero. Drag to reorder.
     */
    items: {
      label: string;
      icon:
        | 'Award'
        | 'CalendarDays'
        | 'Car'
        | 'Clock'
        | 'Heart'
        | 'Palette'
        | 'Settings2'
        | 'Shield'
        | 'ShieldCheck'
        | 'Sparkles'
        | 'SprayCan'
        | 'Star'
        | 'Trophy'
        | 'Users'
        | 'Wind'
        | 'Wrench';
      id?: string | null;
    }[];
  };
  about: {
    /**
     * Small text above the heading
     */
    eyebrow: string;
    title: string;
    body: string;
    image: number | Media;
    /**
     * Shown under the years of experience from Business & SEO
     */
    badgeLabel: string;
    cta: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  transformation: {
    /**
     * Small text above the heading
     */
    eyebrow: string;
    title: string;
    body: string;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    gallery: (number | Media)[];
  };
  packages: {
    /**
     * Small text above the heading
     */
    eyebrow: string;
    title: string;
    /**
     * Packages shown on the Home page. Edit prices in Service Packages.
     */
    services: (number | Service)[];
    cardButton: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
    viewAll: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  ctaBanner: {
    /**
     * Small text above the heading
     */
    eyebrow: string;
    heading: string;
    steps: {
      title: string;
      description: string;
      icon:
        | 'Award'
        | 'CalendarDays'
        | 'Car'
        | 'Clock'
        | 'Heart'
        | 'Palette'
        | 'Settings2'
        | 'Shield'
        | 'ShieldCheck'
        | 'Sparkles'
        | 'SprayCan'
        | 'Star'
        | 'Trophy'
        | 'Users'
        | 'Wind'
        | 'Wrench';
      id?: string | null;
    }[];
    button: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  process: {
    /**
     * Small text above the heading
     */
    eyebrow: string;
    title: string;
    /**
     * Each step is a tab with its own photo
     */
    steps: {
      title: string;
      image: number | Media;
      id?: string | null;
    }[];
    stats?:
      | {
          value: string;
          label: string;
          icon:
            | 'Award'
            | 'CalendarDays'
            | 'Car'
            | 'Clock'
            | 'Heart'
            | 'Palette'
            | 'Settings2'
            | 'Shield'
            | 'ShieldCheck'
            | 'Sparkles'
            | 'SprayCan'
            | 'Star'
            | 'Trophy'
            | 'Users'
            | 'Wind'
            | 'Wrench';
          id?: string | null;
        }[]
      | null;
  };
  testimonials: {
    /**
     * Small text above the heading
     */
    eyebrow: string;
    title: string;
  };
  brands: {
    title: string;
    button: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Packages and prices are edited in Service Packages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero: {
    title: string;
    subtitle: string;
    image: number | Media;
  };
  labels: {
    /**
     * Heading above each package’s list
     */
    includes: string;
    /**
     * Shown above each price, for example Starting at
     */
    price: string;
    bookButton: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  cta: {
    title: string;
    text: string;
    button: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    title: string;
    subtitle: string;
    image: number | Media;
  };
  story: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image: number | Media;
  };
  values: {
    title: string;
    subtitle: string;
    items: {
      title: string;
      description: string;
      icon:
        | 'Award'
        | 'CalendarDays'
        | 'Car'
        | 'Clock'
        | 'Heart'
        | 'Palette'
        | 'Settings2'
        | 'Shield'
        | 'ShieldCheck'
        | 'Sparkles'
        | 'SprayCan'
        | 'Star'
        | 'Trophy'
        | 'Users'
        | 'Wind'
        | 'Wrench';
      id?: string | null;
    }[];
  };
  team: {
    title: string;
    subtitle: string;
    /**
     * Leave empty to hide the team section
     */
    members?:
      | {
          name: string;
          position: string;
          bio?: string | null;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    title: string;
    button: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-page".
 */
export interface BookingPage {
  id: number;
  calendar: {
    /**
     * Turn off to show the unavailable message instead of the calendar
     */
    enabled?: boolean | null;
    /**
     * The part after cal.com/, for example rpm-detailing
     */
    calLink: string;
    /**
     * Optional event name, for example detail
     */
    eventSlug?: string | null;
  };
  content: {
    backLabel: string;
    title: string;
    /**
     * {business} is replaced with the business name
     */
    intro: string;
    loadingText: string;
    helpText: string;
    phoneLabel: string;
    emailLabel: string;
  };
  calendarError: {
    title: string;
    message: string;
    retryLabel: string;
    callLabel: string;
  };
  unavailable: {
    title: string;
    /**
     * {phone} is replaced with the business phone number
     */
    message: string;
    buttonLabel: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Business details, branding and search defaults used across every page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  business: {
    name: string;
    phone: string;
    email: string;
    address: string;
    hours: {
      /**
       * For example Mon - Fri
       */
      days: string;
      /**
       * For example 8:00 am - 6:00 pm or Closed
       */
      time: string;
      id?: string | null;
    }[];
    /**
     * Shown as the badge on the Home page about section
     */
    yearsOfExperience: number;
  };
  branding: {
    /**
     * Shown in the header and footer on a dark background
     */
    logo: number | Media;
    /**
     * Hex colour used for the browser theme and booking calendar
     */
    brandColor: string;
  };
  seo: {
    /**
     * The public address, for example https://rpmdetail.co
     */
    siteUrl: string;
    /**
     * Added after each page title, for example | RPM Detailing
     */
    titleSuffix: string;
    /**
     * Used when a page has no SEO description of its own
     */
    description: string;
    keywords?: string | null;
    /**
     * Used when a page has no SEO image of its own
     */
    image: number | Media;
    /**
     * Without the @
     */
    twitterHandle?: string | null;
  };
  notFound: {
    title: string;
    message: string;
    buttonLabel: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems: {
    label: string;
    type: 'link' | 'contact';
    /**
     * A page like /services or a home page section like #testimonials
     */
    url?: string | null;
    id?: string | null;
  }[];
  showCta?: boolean | null;
  cta?: {
    label: string;
    /**
     * A page like /booking, a home page section like #services, or a full URL
     */
    url: string;
  };
  /**
   * Appears when keyboard users press Tab, to jump past the menu
   */
  skipLinkLabel: string;
  mobileMenu: {
    title: string;
    /**
     * Read aloud by screen readers
     */
    openLabel: string;
    /**
     * Read aloud by screen readers
     */
    closeLabel: string;
  };
  contactPopup: {
    title: string;
    contactHeading: string;
    hoursHeading: string;
    ctaHeading: string;
    ctaText: string;
    ctaButton: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
    /**
     * Read aloud by screen readers
     */
    closeLabel: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description: string;
  contactHeading: string;
  hoursHeading: string;
  cta: {
    heading: string;
    text: string;
    button: {
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  /**
   * {year} is replaced with the current year
   */
  copyright: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        slides?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              id?: T;
            };
        backgroundImage?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        showPhone?: T;
        phoneLabel?: T;
        showAddress?: T;
      };
  servicesBar?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        image?: T;
        badgeLabel?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  transformation?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        gallery?: T;
      };
  packages?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        services?: T;
        cardButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
        viewAll?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  ctaBanner?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  process?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              image?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  brands?:
    | T
    | {
        title?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  labels?:
    | T
    | {
        includes?: T;
        price?: T;
        bookButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  story?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
      };
  values?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        title?: T;
        subtitle?: T;
        members?:
          | T
          | {
              name?: T;
              position?: T;
              bio?: T;
              photo?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-page_select".
 */
export interface BookingPageSelect<T extends boolean = true> {
  calendar?:
    | T
    | {
        enabled?: T;
        calLink?: T;
        eventSlug?: T;
      };
  content?:
    | T
    | {
        backLabel?: T;
        title?: T;
        intro?: T;
        loadingText?: T;
        helpText?: T;
        phoneLabel?: T;
        emailLabel?: T;
      };
  calendarError?:
    | T
    | {
        title?: T;
        message?: T;
        retryLabel?: T;
        callLabel?: T;
      };
  unavailable?:
    | T
    | {
        title?: T;
        message?: T;
        buttonLabel?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  business?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
        hours?:
          | T
          | {
              days?: T;
              time?: T;
              id?: T;
            };
        yearsOfExperience?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        brandColor?: T;
      };
  seo?:
    | T
    | {
        siteUrl?: T;
        titleSuffix?: T;
        description?: T;
        keywords?: T;
        image?: T;
        twitterHandle?: T;
      };
  notFound?:
    | T
    | {
        title?: T;
        message?: T;
        buttonLabel?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        id?: T;
      };
  showCta?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  skipLinkLabel?: T;
  mobileMenu?:
    | T
    | {
        title?: T;
        openLabel?: T;
        closeLabel?: T;
      };
  contactPopup?:
    | T
    | {
        title?: T;
        contactHeading?: T;
        hoursHeading?: T;
        ctaHeading?: T;
        ctaText?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
        closeLabel?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  contactHeading?: T;
  hoursHeading?: T;
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}