/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    testimonials: Testimonial;
    brands: Brand;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'services-page': ServicesPage;
    'about-page': AboutPage;
    'booking-page': BookingPage;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'booking-page': BookingPageSelect<false> | BookingPageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Your detailing packages and prices. Drag to reorder. Shown in this order on the Services page, and as cards on the Home page when featured there.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  /**
   * Package name, shown large on the Services page. Up to 30 characters.
   */
  title: string;
  /**
   * Whole dollars, from 0 to 99,999. 299 is shown as $299.
   */
  price: number;
  /**
   * Optional, shown after the price, for example /month. Up to 10 characters.
   */
  priceSuffix?: string | null;
  /**
   * Optional, for example 4-6 hours. Up to 24 characters.
   */
  duration?: string | null;
  /**
   * Short description for the Home page package cards, which show three lines. Up to 140 characters.
   */
  summary: string;
  /**
   * Full description for the Services page. Paragraphs, bold, italic, links and lists. Up to 1200 characters.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Up to 12 ticked points on the Services page. Optional.
   */
  features?:
    | {
        /**
         * One short point. Up to 60 characters.
         */
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Best size: landscape 4:3, at least 1600 × 1200 px.
   */
  image: number | Media;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos and logos used across the site. JPEG, PNG, WebP or AVIF. Set a focal point to choose what stays in view when a photo is cropped.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo for screen readers and search engines, for example Black sedan after a ceramic coating. Up to 150 characters.
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Customer reviews for the carousel on the Home page. Drag to reorder. Home › Reviews sets how many are shown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  /**
   * The customer’s name. Up to 40 characters.
   */
  name: string;
  /**
   * Optional, for example Regular Client. Up to 40 characters.
   */
  title?: string | null;
  /**
   * The review in the customer’s words. Up to 300 characters.
   */
  review: string;
  /**
   * Optional. Without a photo the customer’s initials are shown. Best size: square, at least 200 × 200 px.
   */
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Car brand logos on the Home page, just above the footer. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  _order?: string | null;
  /**
   * The car brand, for example Porsche. Up to 40 characters.
   */
  name: string;
  /**
   * Shown small and greyed out on a dark background. Best size: a white or light logo on a transparent background, PNG or WebP, at least 400 px wide.
   */
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * People who can sign in to manage the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage users and all content. Editors manage content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  price?: T;
  priceSuffix?: T;
  duration?: T;
  summary?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  title?: T;
  review?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Everything on the Home page, in order from top to bottom. Changes save as a draft until you publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Rotating headlines, 1 to 5. Drag to reorder. With one slide the headline stays still.
     */
    slides: {
      /**
       * Small capitals above the headline. Up to 40 characters.
       */
      eyebrow: string;
      /**
       * The big headline. Keep it under 60 characters so it fits on five lines on phones. Up to 60 characters.
       */
      title: string;
      id?: string | null;
    }[];
    /**
     * Shown behind the headline. Phones show a wide crop across the middle, so set a focal point on the car. Best size: landscape 16:9, at least 1920 × 1080 px.
     */
    backgroundImage: number | Media;
    cta: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
    showPhone?: boolean | null;
    /**
     * Shown before the phone number, for example Call Us: Up to 20 characters.
     */
    phoneLabel: string;
    showAddress?: boolean | null;
  };
  servicesBar: {
    /**
     * The strip of 3 to 6 services under the hero. Drag to reorder.
     */
    items: {
      /**
       * Fits on two short lines on phones. Up to 22 characters.
       */
      label: string;
      icon:
        | 'Award'
        | 'CalendarDays'
        | 'Car'
        | 'Clock'
        | 'Heart'
        | 'Palette'
        | 'Settings2'
        | 'Shield'
        | 'ShieldCheck'
        | 'Sparkles'
        | 'SprayCan'
        | 'Star'
        | 'Trophy'
        | 'Users'
        | 'Wind'
        | 'Wrench';
      id?: string | null;
    }[];
  };
  about: {
    /**
     * Small red capitals above the heading. Up to 40 characters.
     */
    eyebrow: string;
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * Leave a blank line between paragraphs. Up to 600 characters.
     */
    body: string;
    /**
     * Best size: landscape 4:3, at least 1600 × 1200 px.
     */
    image: number | Media;
    /**
     * Shown after the years of experience, for example + makes 5+. Up to 3 characters, or leave empty.
     */
    badgeSuffix?: string | null;
    /**
     * Shown under the years of experience set in Business & SEO. Up to 28 characters.
     */
    badgeLabel: string;
    cta: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  transformation: {
    /**
     * Small red capitals above the heading. Up to 40 characters.
     */
    eyebrow: string;
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * Leave a blank line between paragraphs. Up to 600 characters.
     */
    body: string;
    /**
     * Up to 6 ticked points under the text. Optional.
     */
    features?:
      | {
          /**
           * One short point. Up to 60 characters.
           */
          feature: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Exactly 3 photos. The first is shown tall (portrait 1:2, at least 800 × 1600 px), the other two square (at least 800 × 800 px).
     */
    gallery: (number | Media)[];
  };
  packages: {
    /**
     * Small red capitals above the heading. Up to 40 characters.
     */
    eyebrow: string;
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * Up to 6 packages shown on the Home page. Edit prices in Service Packages.
     */
    services: (number | Service)[];
    cardButton: {
      /**
       * Button text. Up to 14 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
    viewAll: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  ctaBanner: {
    /**
     * Small red capitals above the heading. Up to 40 characters.
     */
    eyebrow: string;
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    heading: string;
    /**
     * Always three steps, shown side by side on large screens.
     */
    steps: {
      /**
       * Step name. Up to 30 characters.
       */
      title: string;
      /**
       * One or two sentences. Up to 160 characters.
       */
      description: string;
      icon:
        | 'Award'
        | 'CalendarDays'
        | 'Car'
        | 'Clock'
        | 'Heart'
        | 'Palette'
        | 'Settings2'
        | 'Shield'
        | 'ShieldCheck'
        | 'Sparkles'
        | 'SprayCan'
        | 'Star'
        | 'Trophy'
        | 'Users'
        | 'Wind'
        | 'Wrench';
      id?: string | null;
    }[];
    button: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  process: {
    /**
     * Small red capitals above the heading. Up to 40 characters.
     */
    eyebrow: string;
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * 2 to 6 steps. Each step is a tab with its own photo.
     */
    steps: {
      /**
       * Tab name, also shown on the photo. Up to 24 characters.
       */
      title: string;
      /**
       * Phones crop the sides to 4:3, so keep the subject near the centre. Best size: landscape 2:1, at least 2000 × 1000 px.
       */
      image: number | Media;
      id?: string | null;
    }[];
    /**
     * Not shown on screen. Read aloud by screen readers, for example Previous step. Up to 40 characters.
     */
    previousLabel: string;
    /**
     * Not shown on screen. Read aloud by screen readers, for example Next step. Up to 40 characters.
     */
    nextLabel: string;
    /**
     * Up to 4 numbers under the photos. Optional.
     */
    stats?:
      | {
          /**
           * Shown very large. Start with a number, for example 850, 1,000+, 24/7 or 100%. Up to 6 characters.
           */
          value: string;
          /**
           * Shown under the number. Up to 24 characters.
           */
          label: string;
          icon:
            | 'Award'
            | 'CalendarDays'
            | 'Car'
            | 'Clock'
            | 'Heart'
            | 'Palette'
            | 'Settings2'
            | 'Shield'
            | 'ShieldCheck'
            | 'Sparkles'
            | 'SprayCan'
            | 'Star'
            | 'Trophy'
            | 'Users'
            | 'Wind'
            | 'Wrench';
          id?: string | null;
        }[]
      | null;
  };
  testimonials: {
    /**
     * Small red capitals above the heading. Up to 40 characters.
     */
    eyebrow: string;
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * How many published reviews to show, 1 to 12, in the order of the Reviews list.
     */
    limit: number;
    /**
     * Not shown on screen. Read aloud by screen readers, for example Previous review. Up to 40 characters.
     */
    previousLabel: string;
    /**
     * Not shown on screen. Read aloud by screen readers, for example Next review. Up to 40 characters.
     */
    nextLabel: string;
  };
  brands: {
    /**
     * Heading above the car brand logos. Up to 60 characters.
     */
    title: string;
    button: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Best size: 1200 × 630 px. Leave empty to use the share image from Business & SEO.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Services page, top to bottom. The packages and prices themselves are edited in Service Packages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero: {
    /**
     * The large page heading. Keep it under 50 characters so it fits on three lines on phones. Up to 50 characters.
     */
    title: string;
    /**
     * One sentence under the heading. Up to 120 characters.
     */
    subtitle: string;
    /**
     * Shown darkened behind the heading. Best size: landscape 16:9, at least 1920 × 1080 px.
     */
    image: number | Media;
  };
  labels: {
    /**
     * Heading above each package’s list. Up to 30 characters.
     */
    includes: string;
    /**
     * Shown above each price, for example Starting at. Up to 20 characters.
     */
    price: string;
    bookButton: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  cta: {
    /**
     * Large heading on the red banner. Up to 60 characters.
     */
    title: string;
    /**
     * One or two sentences under the heading. Up to 200 characters.
     */
    text: string;
    button: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Best size: 1200 × 630 px. Leave empty to use the share image from Business & SEO.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The About page, top to bottom: your story, values and team.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    /**
     * The large page heading. Keep it under 50 characters so it fits on three lines on phones. Up to 50 characters.
     */
    title: string;
    /**
     * One sentence under the heading. Up to 120 characters.
     */
    subtitle: string;
    /**
     * Shown darkened behind the heading. Best size: landscape 16:9, at least 1920 × 1080 px.
     */
    image: number | Media;
  };
  story: {
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * The story beside the photo. Paragraphs, bold, italic, links and lists. Up to 1500 characters.
     */
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Best size: landscape 4:3, at least 1600 × 1200 px.
     */
    image: number | Media;
  };
  values: {
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * One sentence under the heading. Up to 160 characters.
     */
    subtitle: string;
    /**
     * 1 to 6 values. Drag to reorder.
     */
    items: {
      /**
       * Value name. Up to 30 characters.
       */
      title: string;
      /**
       * One or two sentences. Up to 160 characters.
       */
      description: string;
      icon:
        | 'Award'
        | 'CalendarDays'
        | 'Car'
        | 'Clock'
        | 'Heart'
        | 'Palette'
        | 'Settings2'
        | 'Shield'
        | 'ShieldCheck'
        | 'Sparkles'
        | 'SprayCan'
        | 'Star'
        | 'Trophy'
        | 'Users'
        | 'Wind'
        | 'Wrench';
      id?: string | null;
    }[];
  };
  team: {
    /**
     * Section heading. Keep it short so it fits on two or three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * One sentence under the heading. Up to 160 characters.
     */
    subtitle: string;
    /**
     * Up to 6 people. Leave empty to hide the team section.
     */
    members?:
      | {
          /**
           * Full name. Up to 40 characters.
           */
          name: string;
          /**
           * Job title, shown in small red capitals. Up to 40 characters.
           */
          position: string;
          /**
           * A few sentences. Optional. Up to 240 characters.
           */
          bio?: string | null;
          /**
           * Optional. Best size: portrait 4:5, at least 800 × 1000 px.
           */
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    /**
     * Large heading on the red banner. Up to 60 characters.
     */
    title: string;
    button: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Best size: 1200 × 630 px. Leave empty to use the share image from Business & SEO.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Booking page, top to bottom, plus what shows if the calendar fails or booking is off.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-page".
 */
export interface BookingPage {
  id: number;
  content: {
    /**
     * The link back to the home page, top left. Up to 24 characters.
     */
    backLabel: string;
    /**
     * The large page heading. Keep it short so it fits on three lines on phones. Up to 60 characters.
     */
    title: string;
    /**
     * Shown under the heading. {business} is replaced with the business name. Up to 240 characters.
     */
    intro: string;
    /**
     * Shown while the calendar loads. Up to 60 characters.
     */
    loadingText: string;
    /**
     * Shown in the box under the calendar. Up to 80 characters.
     */
    helpText: string;
    /**
     * Shown before the phone number. Up to 16 characters.
     */
    phoneLabel: string;
    /**
     * Shown before the email address. Up to 16 characters.
     */
    emailLabel: string;
  };
  calendar: {
    /**
     * Turn off to show the unavailable message instead of the calendar
     */
    enabled?: boolean | null;
    /**
     * The part after cal.com/, for example rpm-detailing
     */
    calLink: string;
    /**
     * Optional event name, for example detail
     */
    eventSlug?: string | null;
  };
  calendarError: {
    /**
     * Shown if the calendar fails to load. Up to 60 characters.
     */
    title: string;
    /**
     * One or two sentences. Up to 200 characters.
     */
    message: string;
    /**
     * Button text. Up to 24 characters.
     */
    retryLabel: string;
    /**
     * Shown above the phone number. Up to 40 characters.
     */
    callLabel: string;
  };
  unavailable: {
    /**
     * Shown when online booking is turned off. Up to 60 characters.
     */
    title: string;
    /**
     * {phone} is replaced with the business phone number. Up to 200 characters.
     */
    message: string;
    /**
     * Button back to the home page. Up to 24 characters.
     */
    buttonLabel: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Best size: 1200 × 630 px. Leave empty to use the share image from Business & SEO.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The bar at the top of every page, left to right, and the menus it opens.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Up to 6 items. Longer menus switch to the menu button on more screen sizes so they never overlap.
   */
  navItems: {
    /**
     * One or two words. Up to 14 characters.
     */
    label: string;
    type: 'link' | 'contact';
    /**
     * A page like /services or a home page section like #testimonials
     */
    url?: string | null;
    id?: string | null;
  }[];
  /**
   * Appears when keyboard users press Tab, to jump past the menu. Up to 40 characters.
   */
  skipLinkLabel: string;
  showCta?: boolean | null;
  cta?: {
    /**
     * Button text. Up to 16 characters so it stays on one line.
     */
    label: string;
    /**
     * A page like /booking, a home page section like #services, or a full URL
     */
    url: string;
  };
  mobileMenu: {
    /**
     * Small capitals at the top of the menu. Up to 20 characters.
     */
    title: string;
    /**
     * Not shown on screen. Read aloud by screen readers, for example Open menu. Up to 40 characters.
     */
    openLabel: string;
    /**
     * Not shown on screen. Read aloud by screen readers, for example Close menu. Up to 40 characters.
     */
    closeLabel: string;
  };
  contactPopup: {
    /**
     * Heading at the top of the popup. Up to 40 characters.
     */
    title: string;
    /**
     * Small capitals. Up to 24 characters.
     */
    contactHeading: string;
    /**
     * Small capitals. Up to 24 characters.
     */
    hoursHeading: string;
    /**
     * Heading in the booking box. Up to 30 characters.
     */
    ctaHeading: string;
    /**
     * One or two sentences in the booking box. Up to 160 characters.
     */
    ctaText: string;
    ctaButton: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
    /**
     * Not shown on screen. Read aloud by screen readers, for example Close contact details. Up to 40 characters.
     */
    closeLabel: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The dark band at the bottom of every page, left to right. Contact details and opening hours come from Business & SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Shown under the logo. Up to 200 characters.
   */
  description: string;
  /**
   * Small capitals. Up to 24 characters.
   */
  contactHeading: string;
  /**
   * Small capitals. Up to 24 characters.
   */
  hoursHeading: string;
  cta: {
    /**
     * Heading in the booking box. Up to 30 characters.
     */
    heading: string;
    /**
     * One or two sentences in the booking box. Up to 160 characters.
     */
    text: string;
    button: {
      /**
       * Button text. Up to 24 characters so it stays on one line.
       */
      label: string;
      /**
       * A page like /booking, a home page section like #services, or a full URL
       */
      url: string;
    };
  };
  /**
   * The small line at the bottom. {year} is replaced with the current year. Up to 80 characters.
   */
  copyright: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Business details, logo and search defaults used across every page. Change them here once and every page updates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  business: {
    /**
     * Used in page titles, the error page and wherever the logo is missing. Up to 40 characters.
     */
    name: string;
    /**
     * Shown in the header popup, footer, hero and booking page.
     */
    phone: string;
    /**
     * Shown in the footer, contact popup and booking page. Up to 60 characters.
     */
    email: string;
    /**
     * Shown in the hero, footer and contact popup, for example Boise, ID, USA. Up to 80 characters.
     */
    address: string;
    /**
     * One row per day or group of days, up to 7.
     */
    hours: {
      /**
       * For example Mon - Fri. Up to 20 characters.
       */
      days: string;
      /**
       * For example 8:00 am - 6:00 pm or Closed. Up to 30 characters.
       */
      time: string;
      id?: string | null;
    }[];
    /**
     * A whole number from 0 to 99, shown as the badge on the Home page. Use 0 to hide the badge.
     */
    yearsOfExperience: number;
  };
  branding: {
    /**
     * Shown in the header and footer on a dark background. Best size: a white logo on a transparent background, PNG or WebP, at least 600 px wide and about 4 times wider than tall.
     */
    logo: number | Media;
    /**
     * Hex colour used for the browser theme and booking calendar, like #D9232D.
     */
    brandColor: string;
  };
  notFound: {
    /**
     * Shown under the large 404. Up to 40 characters.
     */
    title: string;
    /**
     * One or two sentences. Up to 160 characters.
     */
    message: string;
    /**
     * Button back to the home page. Up to 24 characters.
     */
    buttonLabel: string;
  };
  errorPage: {
    /**
     * Shown if a page fails to load, under the business name. Up to 40 characters.
     */
    title: string;
    /**
     * One or two sentences. Up to 200 characters.
     */
    message: string;
    /**
     * Button that reloads the page. Up to 24 characters.
     */
    retryLabel: string;
  };
  seo: {
    /**
     * Added after each page title in search results, for example | RPM Detailing. Up to 25 characters.
     */
    titleSuffix: string;
    /**
     * Used in search results when a page has no SEO description of its own. At least 50 characters. Up to 160 characters.
     */
    description: string;
    /**
     * Used when a page has no SEO image of its own. Best size: 1200 × 630 px.
     */
    image: number | Media;
    /**
     * The public address, for example https://rpmdetail.co. Only admins can change it.
     */
    siteUrl: string;
    /**
     * Optional, separated by commas. Up to 200 characters.
     */
    keywords?: string | null;
    /**
     * Optional. Without the @.
     */
    twitterHandle?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        slides?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              id?: T;
            };
        backgroundImage?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        showPhone?: T;
        phoneLabel?: T;
        showAddress?: T;
      };
  servicesBar?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        image?: T;
        badgeSuffix?: T;
        badgeLabel?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  transformation?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        gallery?: T;
      };
  packages?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        services?: T;
        cardButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
        viewAll?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  ctaBanner?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  process?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              image?: T;
              id?: T;
            };
        previousLabel?: T;
        nextLabel?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        limit?: T;
        previousLabel?: T;
        nextLabel?: T;
      };
  brands?:
    | T
    | {
        title?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  labels?:
    | T
    | {
        includes?: T;
        price?: T;
        bookButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  story?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
      };
  values?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        title?: T;
        subtitle?: T;
        members?:
          | T
          | {
              name?: T;
              position?: T;
              bio?: T;
              photo?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-page_select".
 */
export interface BookingPageSelect<T extends boolean = true> {
  content?:
    | T
    | {
        backLabel?: T;
        title?: T;
        intro?: T;
        loadingText?: T;
        helpText?: T;
        phoneLabel?: T;
        emailLabel?: T;
      };
  calendar?:
    | T
    | {
        enabled?: T;
        calLink?: T;
        eventSlug?: T;
      };
  calendarError?:
    | T
    | {
        title?: T;
        message?: T;
        retryLabel?: T;
        callLabel?: T;
      };
  unavailable?:
    | T
    | {
        title?: T;
        message?: T;
        buttonLabel?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        id?: T;
      };
  skipLinkLabel?: T;
  showCta?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  mobileMenu?:
    | T
    | {
        title?: T;
        openLabel?: T;
        closeLabel?: T;
      };
  contactPopup?:
    | T
    | {
        title?: T;
        contactHeading?: T;
        hoursHeading?: T;
        ctaHeading?: T;
        ctaText?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
        closeLabel?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  contactHeading?: T;
  hoursHeading?: T;
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  business?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
        hours?:
          | T
          | {
              days?: T;
              time?: T;
              id?: T;
            };
        yearsOfExperience?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        brandColor?: T;
      };
  notFound?:
    | T
    | {
        title?: T;
        message?: T;
        buttonLabel?: T;
      };
  errorPage?:
    | T
    | {
        title?: T;
        message?: T;
        retryLabel?: T;
      };
  seo?:
    | T
    | {
        titleSuffix?: T;
        description?: T;
        image?: T;
        siteUrl?: T;
        keywords?: T;
        twitterHandle?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}