/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    testimonials: Testimonial;
    brands: Brand;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    'landing-page': LandingPage;
    'services-page': ServicesPage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Customer testimonials displayed on the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * Customer's title or vehicle type (e.g., 'Tesla Model 3 Owner')
   */
  title: string;
  review: string;
  avatar?: (number | null) | Media;
  rating?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Car brands/manufacturers displayed on the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  logo: number | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  review?: T;
  avatar?: T;
  rating?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global settings for the entire website including company info, navigation, and branding
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  yearsOfExperience?: number | null;
  hours?: {
    weekdays?: string | null;
    saturday?: string | null;
    sunday?: string | null;
  };
  contactInfo?: {
    additionalPhones?:
      | {
          number: string;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Light version of the logo for dark backgrounds
   */
  logo: number | Media;
  /**
   * Dark version of the logo for light backgrounds
   */
  darkLogo: number | Media;
  description?: string | null;
  /**
   * Use {year} to automatically insert the current year
   */
  copyright?: string | null;
  footerCTA?: {
    heading?: string | null;
    text?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  /**
   * Main navigation menu items. Items will be sorted by order number.
   */
  navigation?:
    | {
        label: string;
        /**
         * Use / for home, /services for services page, #section-name for sections
         */
        link: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  headerCTA?: {
    show?: boolean | null;
    text?: string | null;
    link?: string | null;
  };
  calcom: {
    enabled?: boolean | null;
    /**
     * Your Cal.com username or team slug (e.g., "yourname" for cal.com/yourname)
     */
    link: string;
    /**
     * Optional: specific event type slug (e.g., "30min" for cal.com/yourname/30min)
     */
    eventSlug?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage all content sections for the home/landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  /**
   * The main banner section at the top of the landing page
   */
  hero: {
    title: string;
    subtitle?: string | null;
    backgroundImage: number | Media;
    ctaText?: string | null;
    ctaLink?: string | null;
    showPhoneNumbers?: boolean | null;
    showAddress?: boolean | null;
  };
  /**
   * Quick overview of services shown below the hero section
   */
  servicesBar?:
    | {
        order: number;
        icon?: ('SprayCan' | 'Car' | 'Sparkles' | 'Wind' | 'ShieldCheck' | 'Palette') | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Brief about section on the landing page
   */
  aboutSection: {
    title: string;
    subtitle?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    features?:
      | {
          feature?: string | null;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value: string;
          label: string;
          icon?: ('Users' | 'Car' | 'Award' | 'Settings2' | 'Trophy' | 'Clock') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Detailed service packages shown on the landing page
   */
  detailedServices?:
    | {
        order: number;
        packageId: string;
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Mid-page call-to-action section with process steps
   */
  ctaBanner: {
    heading: string;
    description: string;
    buttonText?: string | null;
    buttonLink?: string | null;
    backgroundImage?: (number | null) | Media;
    preHeading?: string | null;
    ctaItems?:
      | {
          title: string;
          description: string;
          iconName: 'Wrench' | 'CalendarDays' | 'Car' | 'Sparkles' | 'SprayCan';
          id?: string | null;
        }[]
      | null;
  };
  processSection?: {
    /**
     * Small text above the main title
     */
    preHeading?: string | null;
    title?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          order: number;
          title: string;
          active?: boolean | null;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  testimonialsSection?: {
    title?: string | null;
    subtitle?: string | null;
  };
  brandsSection?: {
    title?: string | null;
    subtitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage content for the dedicated services page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  services?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        price?: string | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaButtonText?: string | null;
  ctaButtonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage content for the about us page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  storyTitle?: string | null;
  storyContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  storyImage?: (number | null) | Media;
  values?:
    | {
        title: string;
        description?: string | null;
        /**
         * Lucide icon name (e.g., Shield, Star, Heart)
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  teamTitle?: string | null;
  teamSubtitle?: string | null;
  teamMembers?:
    | {
        name: string;
        position?: string | null;
        bio?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaButtonText?: string | null;
  ctaButtonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  phone?: T;
  email?: T;
  address?: T;
  yearsOfExperience?: T;
  hours?:
    | T
    | {
        weekdays?: T;
        saturday?: T;
        sunday?: T;
      };
  contactInfo?:
    | T
    | {
        additionalPhones?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
      };
  logo?: T;
  darkLogo?: T;
  description?: T;
  copyright?: T;
  footerCTA?:
    | T
    | {
        heading?: T;
        text?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        link?: T;
        order?: T;
        id?: T;
      };
  headerCTA?:
    | T
    | {
        show?: T;
        text?: T;
        link?: T;
      };
  calcom?:
    | T
    | {
        enabled?: T;
        link?: T;
        eventSlug?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        ctaText?: T;
        ctaLink?: T;
        showPhoneNumbers?: T;
        showAddress?: T;
      };
  servicesBar?:
    | T
    | {
        order?: T;
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  aboutSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        content?: T;
        image?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  detailedServices?:
    | T
    | {
        order?: T;
        packageId?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  ctaBanner?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
        backgroundImage?: T;
        preHeading?: T;
        ctaItems?:
          | T
          | {
              title?: T;
              description?: T;
              iconName?: T;
              id?: T;
            };
      };
  processSection?:
    | T
    | {
        preHeading?: T;
        title?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              order?: T;
              title?: T;
              active?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  testimonialsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  brandsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        image?: T;
        price?: T;
        duration?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  ctaButtonText?: T;
  ctaButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  storyTitle?: T;
  storyContent?: T;
  storyImage?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  teamTitle?: T;
  teamSubtitle?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        position?: T;
        bio?: T;
        image?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaButtonText?: T;
  ctaButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}